### ISSUE TITLE
What about AOT compilation?

### ISSUE THREAD

**Issue by BjornMelgaard** [elm-community/elm-webpack-starter#59]
I'm new to language, don't beat me hard

**Comment by eeue56** [comment]
Can you explain a bit what you mean by that?

**Comment by BjornMelgaard** [comment]
As I know all html defined in view function are added at runtime, is it even possible to do some of this work at compile time?

**Comment by eeue56** [comment]
Can you expand a bit further still?

**Comment by BjornMelgaard** [comment]
Don't know, you tell me, thats why I asked)

**Comment by eeue56** [comment]
It's a bit hard to say exactly what you're after without knowing some more context. What's the end goal that you are trying to achieve? A fast page?

**Comment by BjornMelgaard** [comment]
Yes)

**Comment by eeue56** [comment]
My recommendation in that case is to try Elm out. Elm is already pretty fast - it's one of the fastest frontend frameworks out there. When you run into speed issues, join the [Elm slack](https://elmlang.herokuapp.com/) and ask us there! :)

**Comment by BjornMelgaard** [comment]
Thanks)
